# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f161fdc925bae85c28eb3185bd9862ade43d2f2fec7e5a5bc386d711c43fe8078fbd816e39cb0a43fc49ea4d066342bc710c47997c59d5ef296049a44809ea8a

test:
  secret_key_base: 74f7bf36ff67b68cce7db0ad9ca24f45bbd823b2925ac3808c9bd24a44f91944e118ca7878bc3649ef959d22a0ebb84fbb47e97648f22319230d87f52df6f7d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
